version: '3.8'
 
services:
  currencycalc:
    image: currencycalc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data1:/data
    environment:
      - ACCEPT_EULA=Y
  
  post-database:
    image: mysql
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: CurrencyCalc
    ports:
      - 63306:3306

  flyway:
    image: flyway/flyway:10
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - post-database
        
volumes: 
  featurehub-h2-data:
  
  rps_seq_data1: