version: '3.8'
 
services:
  currencycalc:
    image: currencycalc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  post-database:
    image: mysql
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: CurrencyCalc
    ports:
      - 63306:3306

  flyway:
    image: flyway/flyway:10
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - post-database
        
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
  app:
    build:
      context: .
      dockerfile: Demo/Dockerfile
    depends_on: 
      - featurehub
        
volumes: 
  featurehub-h2-data: