version: '3.8'

services:
  currencycalc:
    image: currencycalc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust port mappings as needed

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123  # Change this to your desired root password
      MYSQL_DATABASE: conversion_history  # Change this to your desired database name
      MYSQL_USER: admin  # Change this to your desired database username
      MYSQL_PASSWORD: 123  # Change this to your desired database password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: